# Generated by Django 5.1 on 2024-08-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applied_jobs', '0002_rename_jobs_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_date',
            field=models.DateTimeField(),
        ),
    ]
