# Generated by Django 5.1 on 2024-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applied_jobs', '0004_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='platform',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
