# Generated by Django 5.1 on 2024-09-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applied_jobs', '0007_alter_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='job',
            name='platform',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('INT', 'Interview Invitation'), ('RE', 'Rejected'), ('WI', 'Withdrawn by candidate')], default='PE', max_length=32),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
