# Generated by Django 5.1 on 2024-09-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applied_jobs', '0008_alter_job_company_name_alter_job_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
