# Generated by Django 5.1 on 2024-09-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applied_jobs', '0009_alter_job_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=256),
        ),
    ]
